# Generated by Django 5.0.2 on 2024-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('github', models.CharField(max_length=50)),
                ('leetcode', models.CharField(max_length=50)),
                ('interview', models.CharField(max_length=50)),
                ('linkedin', models.CharField(max_length=50)),
                ('phonenum', models.IntegerField(max_length=50)),
            ],
        ),
    ]
