# Generated by Django 5.0.2 on 2024-03-03 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationForm', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationmodel',
            name='phonenum',
            field=models.IntegerField(),
        ),
    ]
