# Generated by Django 5.0.2 on 2024-03-08 09:00

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationForm', '0003_alter_applicationmodel_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationmodel',
            name='gitProfile',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='gitProgram',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='applicationmodel',
            name='gitSteak',
            field=models.CharField(default=django.utils.timezone.now, max_length=200, unique=True),
            preserve_default=False,
        ),
    ]
