# Generated by Django 5.0.2 on 2024-03-08 09:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ApplicationForm', '0005_alter_applicationmodel_gitprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='applicationmodel',
            name='gitProfile',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='gitProgram',
        ),
        migrations.RemoveField(
            model_name='applicationmodel',
            name='gitSteak',
        ),
    ]
